# Generated by Django 5.1.7 on 2026-07-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_application_class_size_application_competitions_won_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='final_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_level',
            field=models.CharField(blank=True, choices=[('Masters', 'Masters'), ('PhD', 'PhD'), ('Both', 'Both'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='enrollment_batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='generated_letter',
            field=models.FileField(blank=True, upload_to='generated_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='generated_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_applications', to='home.customtemplates'),
        ),
        migrations.AddField(
            model_name='application',
            name='known_roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passed_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='professional_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='strong_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='weak_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='years_known',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
