# Generated by Django 5.1.7 on 2026-07-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_intake_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplates',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtemplates',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teacherinfo'),
        ),
    ]
