# Generated by Django 5.1.7 on 2026-07-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_seed_system_templates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customtemplates',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('professor__isnull', True)), models.Q(('is_system', False), ('professor__isnull', False)), _connector='OR'), name='template_system_xor_owned'),
        ),
    ]
