# Generated by Django 5.1.7 on 2026-07-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_collapse_duplicate_qualities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualities',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.application'),
        ),
    ]
