# Generated by Django 5.1.7 on 2026-08-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_link_teacher_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
