# Generated by Django 5.1.7 on 2026-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_seed_full_letter_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_pro',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
